In [35]:
import os
import pandas as pd
from textblob import *
import nltk
import numpy as np
import openpyxl
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from textblob import *



data = pd.read_csv("tftest.csv")
data

,title,text,flag
0,Barca's Valverde skirts independence debate as...,"MADRID, (Reuters) - Barcelona boss Ernesto Val...",1.0
1,"Alleged Kenyan police killing of girl, baby in...",NAIROBI (Reuters) - Kenya s police monitor sai...,1.0
2,Father Of Orlando Shooter Says His Son Got An...,The shooter responsible for a mass shooting th...,0.0
3,U.N. seeks humanitarian pause in Sanaa where s...,GENEVA (Reuters) - The United Nations called o...,1.0
4,FBI WARNS Of Potential Terror Attack At SUPER ...,Wouldn t it be great if the Obama administrati...,0.0
...,...,...,...
995,Factbox: Who will Trump pick to lead the Feder...,(Reuters) - U.S. President Donald Trump has in...,1.0
996,Battle over bathrooms looms large in North Car...,"WINSTON-SALEM, N.C. (Reuters) - In a year of p...",1.0
997,Trump dismisses Buffett's rebuke over his busi...,WASHINGTON (Reuters) - U.S. Republican preside...,1.0
998,"Trump may have stopped the bleeding, but not t...",WASHINGTON (Reuters) - Donald Trump may have ...,1.0
999,Indonesia prepares to divert Bali-bound flight...,JAKARTA (Reuters) - Indonesian authorities are...,1.0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

stop_words = stopwords.words("english")
corpus = data["text"]
vectorizer = TfidfVectorizer(strip_accents="ascii", lowercase=True, stop_words=stop_words, max_features=None)
features = np.transpose(vectorizer.fit_transform(corpus).toarray())
names = vectorizer.get_feature_names_out()

feature_frame = pd.DataFrame(features, columns=names)
feature_frame


data = pd.concat([data, feature_frame], axis=1)

data

,title,text,flag,000,10,100,11,12,14,15,...,world,would,wrong,wrote,year,years,yet,york,young,youtube
0,Barca's Valverde skirts independence debate as...,"MADRID, (Reuters) - Barcelona boss Ernesto Val...",1.0,0.000000,0.035791,0.000000,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.116298,0.000000,0.0,0.151154
1,"Alleged Kenyan police killing of girl, baby in...",NAIROBI (Reuters) - Kenya s police monitor sai...,1.0,0.000000,0.000000,0.000000,0.108649,0.0,0.0,0.000000,...,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.088113
2,Father Of Orlando Shooter Says His Son Got An...,The shooter responsible for a mass shooting th...,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
3,U.N. seeks humanitarian pause in Sanaa where s...,GENEVA (Reuters) - The United Nations called o...,1.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
4,FBI WARNS Of Potential Terror Attack At SUPER ...,Wouldn t it be great if the Obama administrati...,0.0,0.000000,0.046600,0.140697,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.050472,0.075779,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Factbox: Who will Trump pick to lead the Feder...,(Reuters) - U.S. President Donald Trump has in...,1.0,0.067098,0.000000,0.000000,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.00000,0.0,0.000000,0.056569,0.000000,0.096620,0.0,0.000000
996,Battle over bathrooms looms large in North Car...,"WINSTON-SALEM, N.C. (Reuters) - In a year of p...",1.0,0.000000,0.000000,0.058587,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.00000,0.0,0.073973,0.000000,0.000000,0.000000,0.0,0.000000
997,Trump dismisses Buffett's rebuke over his busi...,WASHINGTON (Reuters) - U.S. Republican preside...,1.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.029605,...,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.000000,0.065166,0.0,0.000000
998,"Trump may have stopped the bleeding, but not t...",WASHINGTON (Reuters) - Donald Trump may have ...,1.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
999,Indonesia prepares to divert Bali-bound flight...,JAKARTA (Reuters) - Indonesian authorities are...,1.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.08883,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

   0  1
0  1  4
1  2  5
2  3  6